### ISSUE TITLE
Reaction menu isn't disabled for self-destructing media

### ISSUE THREAD

**Issue by SandaruKasa** [TGX-Android/Telegram-X#201] opened 2022-08-07 20:00 UTC
I don't think I can provide any screenshots, because Telegram X seems to be blocking the screenshots whenever any self-destructing media is present on the screen, even if not in the opened state. So sorry for that.

## Actual behavior
The context menu (that appears after tapping on the message) has the row with reaction buttons even if the message in question is a self-destruct photo/video. Pressing on any of the reactions cause the reaction to not go through and a small bubble saying `#400: MESSAGE_ID_INVALID` appear at the top part of the screen. 

## Expected behavior
The context menu for self-destruct media doesn't have any reaction buttons.

## Report deatils
Telegram X 0.24.10.1539-arm64-v8a (73c3eef7)
PRs: #185 (81bd52c0)
TDLib: 1.8.4 (tdlib/td@98bfbc9)
Android: Pie (28)
Device: asus ZB602KL (PKQ1.WW_Phone-16.2017.2009.087-20200826)

**Comment by EDINAM233** [comment] 2022-08-08 09:14
Well with  Telegram x you need to got to setting menu from there you will know where to tick the allow screenshot

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: SandaruKasa ***@***.***>
Sent: Sunday, August 7, 2022 8:00:31 PM
To: TGX-Android/Telegram-X ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TGX-Android/Telegram-X] Reaction menu isn't disabled for self-destructing media (Issue #201)


I don't think I can provide any screenshots, because Telegram X seems to be blocking the screenshots whenever any self-destructing media is present on the screen, even if not in the opened state. So sorry for that.

Actual behavior

The context menu (that appears after tapping on the message) has the row with reaction buttons even if the message in question is a self-destruct photo/video. Pressing on any of the reactions cause the reaction to not go through and a small bubble saying #400: MESSAGE_ID_INVALID appear at the top part of the screen.

Expected behavior

The context menu for self-destruct media doesn't have any reaction buttons.

Report deatils

Telegram X 0.24.10.1539-arm64-v8a (73c3eef<https://github.com/TGX-Android/Telegram-X/commit/73c3eef798b44667a0553d6aedd68af6b16952f7>)
PRs: #185<https://github.com/TGX-Android/Telegram-X/pull/185> (81bd52c<https://github.com/TGX-Android/Telegram-X/commit/81bd52c0c75e8d4e059ebde52d30a64eb9cdaaeb>)
TDLib: 1.8.4 ***@***.***<https://github.com/tdlib/td/commit/98bfbc9>)
Android: Pie (28)
Device: asus ZB602KL (PKQ1.WW_Phone-16.2017.2009.087-20200826)

**Comment by vkryl** [comment] 2022-08-08 09:42
@SandaruKasa thank you for the well-described report. Will be fixed soon on TDLib side.

**Comment by vkryl** [comment] 2022-10-28 00:11
Should be fixed since 88b5a9c, you can check in the last beta available on Google Play or https://t.me/tgx_log.

**Closed by vkryl** 2022-10-28 00:11 UTC
Labels: tdlib
