### ISSUE TITLE
Unable to reply to a message if it's opened from Chat info -> Message from user

### ISSUE THREAD

**Issue by aNNiMON** [TGX-Android/Telegram-X#681] opened 2024-06-24 14:41 UTC
## Steps to reproduce:

1. Open a group chat info
2. Choose any member -> Long tap -> Messages from user
3. In the messages screen tap on any message and select Reply
or
4. In the messages screen tap on any message and select Show in chat
5. Click on the message once again and select Reply

## Actual result

Keyboard appears, but the input is hidden by the Chat info screen

https://github.com/TGX-Android/Telegram-X/assets/1321838/a5c64fd6-8c57-46c1-8403-049c8b2b1751

## Expected result

The message input is not hidden by chat info, message search layout is closed

----

Telegram X 0.26.9.1730-arm64-v8a (7bc96dbf)
TDLib: 1.8.30 (tdlib/td@b102c3a)
Android: 14 (34)
Device: OnePlus OnePlus LE2101 (LE2101_14.0.0.600(EX01))
Screen: 2297x1080 (density: 2.55, fps: 120.00001)
Build: OnePlus/OnePlus9R_IND/OnePlus9R:14/UKQ1.230924.001/R.17b0fc4-1-2:user/release-keys
Package: org.thunderdog.challegram
Locale: en_UA (app: en)
Installer: Google Play
Initiator: Google Play
APK Fingerprint: 66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68

**Comment by Sajilck** [comment] 2024-06-24 17:34
Duplicate of #355

**Closed by Sajilck** 2024-06-24 17:34 UTC
