### ISSUE TITLE
Fingerprint unlock is requested twice.

### ISSUE THREAD

**Issue by f242** [TGX-Android/Telegram-X#223] opened 2022-09-16 22:40 UTC
redmi 9 pro plus
android 12
tgx 0.25.0.1555-arm64-v8a from google play

Displays the numeric keypad for the pin code in the background Telegram X and the fingerprint request.
Displays an open chat in the background and prompts for fingerprint again.

**Comment by vkryl** [comment] 2022-09-17 02:16
Duplicate of #210

**Closed by vkryl** 2022-09-17 02:16 UTC

**Comment by nobodeex** [comment] 2023-03-10 09:29
I experience the same bug on my OnePlus 7T. It is NOT a duplicate of #210 as @vkryl falsely states! 
In #210 the fingerprint operation is cancelled, whereas in this case it successfully completes but shows the prompt a second time, showing the unlocked app in the background. The second prompt is then skippable, distinguishing this bug clearly from #210. 

This behaviour has been described in different posts on different forums since 2019 and ignored just as long. 
I think it is high time to read bug reports carefully before flagging them duplicate and simply closing them and to adress this glaring bug in basic functionality like professional developers usually do :)
